parameters:
  app.log_file_path: '/var/www/source/log/oe_moduletemplate.log'

imports:
  - { resource: src/Settings/services.yaml }

services:

  _defaults:
    public: false
    autowire: true

  OxidSolutionCatalysts\TeleCash\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true