imports:
  - { resource: src/Settings/services.yaml }
  - { resource: src/Core/services.yaml }
services:

  _defaults:
    public: false
    autowire: true

  OxidSolutionCatalysts\TeleCash\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true