install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-solution-catalysts/telecash-module": "{{ .Data.global.composer.ref_name }}"
          },
          "repositories": {
            "oxid-solution-catalysts/telecash-module": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/telecash-module"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:module:activate osc_telecash

runscript: &runscript
  matrix:
    script: |
      [
        "osc_telecash:tests-unit",
        "osc_telecash:tests-integration",
        "osc_telecash:tests-codeception"
      ]
  osc_telecash:
    path: 'vendor/oxid-solution-catalysts/telecash-module'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "osc_telecash:phpcs-report",
        "osc_telecash:phpmd-report",
        "osc_telecash:phpstan-report"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-solution-catalysts/telecash-module/'
  project_key: 'OXID-eSales_telecash-module'
  project_name: 'oxid-solution-catalysts/telecash-module'
  organization: 'oxid-esales'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Dsonar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: 'Module template ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
