services:
  _defaults:
    public: false
    autowire: true

  OxidSolutionCatalysts\TeleCash\Core\Service\Logger:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\Logger
    public: true
    arguments:
      - '@OxidSolutionCatalysts\TeleCash\Logger'

  OxidSolutionCatalysts\TeleCash\Core\Service\Context:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\Context
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\OxNewService:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\OxNewService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\RegistryService:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\RegistryService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\TranslateServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\TranslateService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashAfterProcessServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashAfterProcessService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashAPIServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashAPIService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashPaymentValidatorServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\TeleCashPaymentValidatorService
    public: true

  OxidSolutionCatalysts\TeleCash\Core\Service\ErrorDisplayServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Core\Service\ErrorDisplayService
    public: true

  OxidSolutionCatalysts\TeleCash\Logger:
    class: Monolog\Logger
    factory: ['@OxidSolutionCatalysts\TeleCash\Logger\Factory', 'create']
    public: true

  OxidSolutionCatalysts\TeleCash\Logger\Factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\MonologLoggerFactory
    public: true
    arguments:
      $configuration: '@OxidSolutionCatalysts\TeleCash\Logger\Configuration'

  OxidSolutionCatalysts\TeleCash\Logger\Configuration:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfiguration
    public: true
    arguments:
      $loggerName: 'TeleCash Payment Logger'
      $logFilePath: '@=service("OxidSolutionCatalysts\\TeleCash\\Core\\Service\\Context").getTeleCashLogFilePath()'
      $logLevel: '@=service("OxidSolutionCatalysts\\TeleCash\\Settings\\Service\\ModuleSettingsServiceInterface").getLogLevel() ?: "error"'
