services:
  _defaults:
    public: false
    autowire: true

  OxidSolutionCatalysts\TeleCash\Settings\Service\ModuleSettingsServiceInterface:
    class: OxidSolutionCatalysts\TeleCash\Settings\Service\ModuleSettingsService
    public: true
